defmodule Avoidit.Repo.Migrations.UpdateEmailSourceRelationship do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:sources, "sources_email_id_fkey")

    alter table(:sources) do
      modify :email_id,
             references(:emails,
               column: :id,
               name: "sources_email_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    create index(:sources, [:email_id])
  end

  def down do
    drop_if_exists index(:sources, [:email_id])

    drop constraint(:sources, "sources_email_id_fkey")

    alter table(:sources) do
      modify :email_id,
             references(:emails,
               column: :id,
               name: "sources_email_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end
  end
end
