defmodule Avoidit.Repo.Migrations.AddEmailSourceRelationships do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:sources) do
      add :email_id,
          references(:emails,
            column: :id,
            name: "sources_email_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:sources, "sources_email_id_fkey")

    alter table(:sources) do
      remove :email_id
    end
  end
end
