defmodule Avoidit.Repo.Migrations.AddEmailAddressToEmails do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:emails) do
      add :email_address, :text, null: false
    end
  end

  def down do
    alter table(:emails) do
      remove :email_address
    end
  end
end
